language: perl
perl:
  - "5.18"
  - "5.16"
# NEED FIX: Perl v5.14 compiler errors, temporarily disable
#  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

notifications:
  irc:
    channels:
      - "irc.perl.org#perl11"
    on_success: always
    on_failure: always
    # to enable skip_join, in IRC channel first execute `/mode -n`
    skip_join: true
    template:
      - "RPerl Commit By %{author}. %{message} %{build_url}"

    # DEFAULT TEMPLATE
#      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
#      - "Change view : %{compare_url}"
#      - "Build details : %{build_url}"
