language: perl
perl:
# NEED FIX? Perl v5.8 $CPP_LINKED global symbol errors, leave disabled?
#  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"

before_script:
# UNCOMMENT LINE BELOW TO ENABLE NOISY BUILD & STDOUT IN 'make'
    - "export TEST_VERBOSE=1"
# travis already calls `cpanm --quiet --installdeps --notest .` itself
# UNCOMMENT LINE BELOW FOR DEV VERSIONS OF MODULES, which travis can't get from Makefile.PL
#  - cpanm -n INGY/Inline-C-0.62_03.tar.gz

# replace default build command "perl Makefile.PL && make test"
# DEV NOTE: TEST_VERBOSE variable for ExtUtils::MakeMaker 'make' command disables suppression of stdout;
# this variable is different than, and inherits the value of, the $TEST_VERBOSE environmental variable 
# used by RPerl for setting Inline's build_noisy, etc.
script: "perl Makefile.PL && make test TEST_VERBOSE=$TEST_VERBOSE"

notifications:
  irc:
    channels:
      - "irc.perl.org#perl11"
    on_success: always
    on_failure: always
    # to enable skip_join, in IRC channel first execute `/mode -n`
    skip_join: true
    template:
      - "RPerl build %{result}. %{author} says '%{commit_message}'"
      - "%{build_url} %{compare_url}"

    # DEFAULT TEMPLATE
#      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
#      - "Change view : %{compare_url}"
#      - "Build details : %{build_url}"
