language: perl
perl:
# NEED FIX? Perl v5.8 $CPP_LINKED global symbol errors, leave disabled?
#  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"

# travis already calls `cpanm --quiet --installdeps --notest .` itself
# but we still require a dev version
before_script:
  - cpanm -n INGY/Inline-C-0.62_03.tar.gz

notifications:
  irc:
    channels:
      - "irc.perl.org#perl11"
    on_success: always
    on_failure: always
    # to enable skip_join, in IRC channel first execute `/mode -n`
    skip_join: true
    template:
      - "RPerl Build %{result}; %{author}; %{commit_message}"
      - "%{build_url} %{compare_url}"

    # DEFAULT TEMPLATE
#      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
#      - "Change view : %{compare_url}"
#      - "Build details : %{build_url}"
