language: perl
perl:
# NEED FIX? Perl v5.8 $CPP_LINKED global symbol errors, leave disabled?
#  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"

# travis already calls `cpanm --quiet --installdeps --notest .` itself
#before_script:
#  - cpanm --installdeps .

notifications:
  irc:
    channels:
      - "irc.perl.org#perl11"
    on_success: always
    on_failure: always
    # to enable skip_join, in IRC channel first execute `/mode -n`
    skip_join: true
    template:
      - "RPerl Commit By %{author}: %{commit}"
      - "%{message} %{build_url}"

    # DEFAULT TEMPLATE
#      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
#      - "Change view : %{compare_url}"
#      - "Build details : %{build_url}"
