language: perl
perl:
  - "5.18"
  - "5.16"
# NEED FIX: Perl v5.14 compiler errors, temporarily disable
#  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

notifications:
  irc:
    channels:
      - "irc.perl.org#perl11"
    on_success: never
    on_failure: always
